now |weights| < 1 in periodic domain

diff --git a/tools/advect_latlon.sh.in b/tools/advect_latlon.sh.in
--- a/tools/advect_latlon.sh.in
+++ b/tools/advect_latlon.sh.in
@@ -3,61 +3,57 @@
 export DYLD_LIBRARY_PATH=$VTK_DIR/../..
 export LD_LIBRARY_PATH=$VTK_DIR/../..
 
-NX=36
-NY=18
+NX=4
+NY=3
 #STREAM_FUNC="(sin((pi*(x-2*y))/360.)+sin((pi*(x+2*y))/360.))/2."
 #STREAM_FUNC="(cos((pi*(x-2*y))/360.)+cos((pi*(x+2*y))/360.))/2."
 #STREAM_FUNC="sin(pi*(x-321.)/(331.-321.))*(heaviside(y-0.,1.)-heaviside(y-81.,1.))*(heaviside(x-300,1.)-heaviside(x-310,1.))/(331.-321.)"
-STREAM_FUNC="sin(pi*(x-320.)/(320.-300.))*(heaviside(x-300,1.)-heaviside(x-320,1.))/(320.-300.)"
-U="0*x+20."
+xlo="(-360.)"
+xhi="720."
+ylo="(-91.)"
+yhi="(-89.)"
+sfuncx="heaviside(x-$xlo,1.)-heaviside(x-$xhi,1.)" #"sin(pi*(x-$xhi)/($xhi-$xlo))*(heaviside(x-$xlo,1.)-heaviside(x-$xhi,1.))"
+sfuncy="heaviside(y-$ylo,1.)-heaviside(y-$yhi,1.)" #"sin(pi*(y-$ylo)/($yhi-$ylo))*(heaviside(y-$ylo,1.)-heaviside(y-$yhi,1.))"
+STREAM_FUNC="($sfuncx)*($sfuncy)"
+U="0*x" #+90."
 V="0*x"
-#U="5*2*(cos(pi*(x-2*y)/360.)-cos(pi*(x+2*y)/360.))"
-#V="5*1*(cos(pi*(x-2*y)/360.)+cos(pi*(x+2*y)/360.))"
-NSTEPS=20
+NSTEPS="5"
 DT=1
 
 
-# generate grid.nc:physics with edge_integrated_velocity
-echo "generating lat lon grid..."
-python @CMAKE_SOURCE_DIR@/tools/generate_latlon_ugrid.py -nx $NX -ny $NY -s $STREAM_FUNC -o grid.nc:physics
+# generate grid.nc:physics grid
+echo "generate lat lon grid..."
+python @CMAKE_SOURCE_DIR@/tools/generate_latlon_ugrid.py -nx $NX -ny $NY -s $STREAM_FUNC -o "grid.nc:physics"
 if [ $? != 0 ]; then
     echo "ERROR when running generate_latlon_ugrid.py"
     exit 1
 fi
 
-echo "add edge field from stream function..."
-python @CMAKE_SOURCE_DIR@/tools/generate_edge_field.py -g grid.nc:physics -d input_data.nc \
-       -n edge_integrated_velocity -s $STREAM_FUNC
+# push the grid upstream grid
+echo "push the grid upstream..."
+python @CMAKE_SOURCE_DIR@/tools/generate_upstream_grid.py -u $U -v $V -g "grid.nc:physics" -o upstream.nc -t $DT
 if [ $? != 0 ]; then
-    echo "ERROR when running generate_edge_field.py"
-    exit 1
-fi
-
-cp input_data.nc input_data_initial.nc
-
-# saving the grid in VTK file. NOTE the -r option, which turns off regularization for the lat lon grid
-echo "saving grid in VTK file grid.vtk..."
-python @CMAKE_SOURCE_DIR@/tools/ugrid_reader.py -i grid.nc:physics -r -V grid.vtk -stream $STREAM_FUNC -u "$U" -v "$V"
-if [ $? != 0 ]; then
-    echo "ERROR when running ugrid_reader.py"
+    echo "ERROR when running generate_upstream_grid.py"
     exit 2
 fi
 
-# push the grid upstream grid
-echo "pushing the grid upstream..."
-python @CMAKE_SOURCE_DIR@/tools/generate_upstream_grid.py -u $U -v $V -g grid.nc:physics -o upstream.nc -t $DT
-if [ $? != 0 ]; then
-    echo "ERROR when running generate_upstream_grid.py"
-    exit 3
-fi
-
-# compute the regridding weights
-@CMAKE_BINARY_DIR@/tools/regrid_edges -s grid.nc:physics -S 0 \
-                                      -d "upstream.nc:physics" -D 0 \
+# compute the regridding weights, tell the grid it is periodic
+echo "compute the regridding weights"
+@CMAKE_BINARY_DIR@/tools/regrid_edges -s "upstream.nc:physics" -S 0 \
+                                      -d "grid.nc:physics" -D 0 \
                                       -w weights.nc -N 128 -debug 2 -P 360
 if [ $? != 0 ]; then
     echo "ERROR when computing the regridding weights"
-    exit 4
+    exit 3
+fi
+
+
+echo "generate edge data on upstream grid..."
+python @CMAKE_SOURCE_DIR@/tools/generate_edge_field.py -g upstream.nc:physics -d upstream_data.nc \
+       -n edge_integrated_velocity -s $STREAM_FUNC
+if [ $? != 0 ]; then
+    echo "ERROR when running generate_edge_field.py"
+    exit 3
 fi
 
 # step in time
@@ -66,30 +62,43 @@ for step in $(seq -f "%05g" 0 $NSTEPS1); do
 
     echo "step $step"
 
-    ncdump input_data.nc | grep -i nan
-
-    # regrid from current to upstream
-    @CMAKE_BINARY_DIR@/tools/regrid_edges -s grid.nc:physics -S 0 \
-                                          -d upstream.nc:physics -D 0 \
+    # regrid from upstream to grid
+    @CMAKE_BINARY_DIR@/tools/regrid_edges -s upstream.nc:physics -S 0 \
+                                          -d grid.nc:physics -D 0 \
                                           -W weights.nc \
-                                          -v edge_integrated_velocity@input_data.nc \
-                                          -o upstream_${step}.vtk -O data_${step}.nc
+                                          -v edge_integrated_velocity@upstream_data.nc \
+                                          -o grid_${step}.vtk -O data_${step}.nc
     if [ $? != 0 ]; then
         echo "ERROR when applying the regridding weights"
+        exit 4
+    fi
+
+    # saving the grid in VTK file. NOTE the -r option, which turns off regularization for the lat lon grid
+    #echo "saving grid in VTK file grid.vtk..."
+    #python @CMAKE_SOURCE_DIR@/tools/ugrid_reader.py -i grid.nc:physics -r -V grid.vtk -stream $STREAM_FUNC -u "$U" -v "$V"
+    #if [ $? != 0 ]; then
+    #    echo "ERROR when running ugrid_reader.py"
+    #    exit 2
+    #fi
+
+       
+    # convert field saved cell by cell to edge field with unique edge Ids                               
+    python @CMAKE_SOURCE_DIR@/tools/cellByCell2Edges.py -i grid_${step}_0.vtk -v edge_integrated_velocity -o edge_${step}.vtk
+    if [ $? != 0 ]; then
+        echo "ERROR when converting cell-by-cell field to edge field with unique edge Ids"
         exit 5
     fi
 
-    ncdump data_${step}.nc | grep -i nan
-    mv upstream_${step}_0.vtk upstream_${step}.vtk
-       
-    # convert field saved cell by cell to edge field with unique edge Ids                               
-    python @CMAKE_SOURCE_DIR@/tools/cellByCell2Edges.py -i upstream_${step}.vtk -v edge_integrated_velocity -o edge_upstream_${step}.vtk
-    if [ $? != 0 ]; then
-        echo "ERROR when converting cell-by-cell field to edge field with unique edge Ids"
-        exit 6
-    fi
-
     # save the data for this time step
-    cp data_${step}.nc input_data.nc
+    cp data_${step}.nc upstream_data.nc
 done
+
+
+
+
+
+
+
+
+
 
